-- Seed training days
INSERT OR IGNORE INTO training_days (id, title, subtitle, description, order_num) VALUES 
(1, '1. nap', 'Vezetői tudatosság és problémamegoldás', 'Strukturált problémafeltárás és gyökérok-elemzés', 1),
(2, '2. nap', 'Vezetői stílus és stratégiaalkotás', 'Jövőkép megfogalmazása és akciótervezés', 2),
(3, '3. nap', 'Csapat kialakítása', 'Szerepek, felelősségek és kompetenciák', 3),
(4, '4. nap', 'Teljesítménymenedzsment', 'KPI-ok, mérés és visszajelzési rendszerek', 4),
(5, '5. nap', 'Csapatmenedzsment', 'Delegálás, motiváció és konfliktuskezelés', 5),
(6, '6. nap', 'Fenntartás & adaptáció', 'Változás beépítése és folyamatos fejlődés', 6);

-- Seed training steps for Day 1
INSERT OR IGNORE INTO training_steps (day_id, step_number, title, description, tools, importance, limitations, instructions) VALUES 
(1, 1, 'Problémák, kihívások azonosítása', 
 'Összegyűjtsd azokat a problémákat és kihívásokat, amelyek a saját munkakörnyezetedben valóban jelen vannak, és amelyekre van ráhatásod.',
 '["Brainstorming", "Pulse check", "Megfigyelés", "Interjúk", "Adatok áttekintése"]',
 'A jól megválasztott probléma az egész feladat és a tanulási folyamat sikerének alapja.',
 'A túl nagy, túl általános vagy a saját befolyási körön kívül eső problémák kezelhetetlenek lesznek.',
 'Írd fel az 5 legégetőbb szervezeti/üzleti problémát. Ne gondolkozz sokat – írj gyorsan, intuitívan. Légy konkrét, fókuszálj olyan problémákra, amelyekre van ráhatásod.'),

(1, 2, 'Hatáselemzés',
 'Feltérképezd, milyen hatásai vannak a problémának a szervezet különböző területeire.',
 '["Cost-Benefit elemzés", "FMEA", "Erőtér-elemzés", "ROI"]',
 'Világossá teszi a probléma következményeit és így támogatja a tudatos döntéshozatalt.',
 'Az eredmények a feltételezések és adatok megbízhatóságától függenek.',
 'Válaszd ki a 3 legfontosabb problémát. Minden problémához válassz 1 eszközt. Töltsd ki az elemzési táblát.'),

(1, 3, 'Problémaelemzés',
 'A probléma részeire bontva, rendszerezve megértsük, mi alkotja a teljes képet.',
 '["Pareto-elemzés", "Affinitás-diagram", "Folyamatábra", "DILO/WILO"]',
 'A problémák gyakran sokféle apró tényezőből állnak össze. Ha nem strukturáljuk, könnyen rossz területre fordítjuk az erőforrást.',
 'Az elemzéshez sok és pontos adat kell, különben torz képet ad.',
 'Válaszd ki az elemzendő problémát. Válassz eszközt a táblázatból. Végezd el az elemzést.'),

(1, 4, 'Priorizálás',
 'Eldöntsd, a sok azonosított probléma közül melyik a legfontosabb és legsürgetőbb.',
 '["Hatás-Ráfordítás mátrix", "Döntési mátrix", "Pareto-elv", "Eisenhower-mátrix"]',
 'Nem minden problémát lehet egyszerre kezelni. Ha nincs fókusz, a szervezet szétforgácsolja erőforrásait.',
 'Szubjektív értékelés könnyen torzíthatja az eredményt.',
 'Értékelj minden problémát 1-5 skálán hatás és erőfeszítés alapján. Helyezd el őket a mátrixon.'),

(1, 5, 'Problémameghatározás',
 'Világosan, röviden és mindenki számára érthetően rögzítsd, pontosan miről van szó.',
 '["5W1H keretrendszer", "SMART logika", "Canvas módszer", "Probléma definíció sablon"]',
 'A rosszul definiált problémát nem lehet helyesen megoldani.',
 'Gyakori hiba, hogy a megfogalmazás már tartalmazza a megoldást.',
 'Válaszolj minden kérdésre konkrétan és részletesen az 5W1H keretrendszer szerint.'),

(1, 6, 'Kontextus leírása',
 'Feltárni a probléma hátterét, környezetét és kapcsolódó tényezőit.',
 '["SWOT-analízis", "PESTEL-elemzés", "Stakeholder-elemzés"]',
 'A problémák gyakran más tényezők következményei. Ha nem értjük a környezetet, a megoldás sem lesz tartós.',
 'Könnyen túl szélesre nyúlhat, ha minden tényezőt megpróbálunk vizsgálni.',
 'Helyezd kontextusba a problémát a szervezeti környezetben SWOT és stakeholder elemzéssel.'),

(1, 7, 'Adatok és tények gyűjtése',
 'Összegyűjteni minden releváns információt: mérőszámokat, statisztikákat, visszajelzéseket.',
 '["Adatgyűjtő lap", "Kérdőívek", "KPI mérések", "Dokumentumelemzés"]',
 'Az adatok nemcsak igazolják a probléma létezését, de baseline-ként szolgálnak a későbbi javulás méréséhez.',
 'Nem minden problémánál áll rendelkezésre elegendő adat.',
 'Határozd meg, milyen adatra van szükséged. Gyűjtsd össze és számszerűsítsd a jelenlegi állapotot.'),

(1, 8, 'Gyökérok-elemzés',
 'Biztosítani, hogy ne csak a felszínt kapargassuk, hanem a probléma gyökeréig leássunk.',
 '["5 Miért módszer", "Ishikawa diagram", "Pareto-elemzés"]',
 'Gyakran egy tüneti kezeléssel csak átmeneti javulást érünk el.',
 'Nehéz lehet a valódi gyökérokot elválasztani a másodlagos okoktól.',
 'Kérdezz rá sorozatban legalább ötször a "Miért?" kérdésre. Használd az Ishikawa diagramot.');

-- Seed training steps for Day 2
INSERT OR IGNORE INTO training_steps (day_id, step_number, title, description, tools, importance, limitations, instructions) VALUES 
(2, 1, 'Miért? – Start with Why',
 'Megtalálni és megfogalmazni a mélyebb célodat, azt a "Miért"-et, ami motivál.',
 '["Golden Circle", "Purpose Canvas", "5 Whys (Purpose verzió)"]',
 'Az emberek nem azt veszik meg, amit csinálsz, hanem azt, amiért csinálod.',
 'A "Miért" megtalálása nehéz – őszinte önreflexiót igényel.',
 'Töltsd ki a Golden Circle: Mit csinálsz? Hogyan csinálod? Miért csinálod?'),

(2, 2, 'Vízió megfogalmazása',
 'Egy világos, inspiráló képet alkotni arról, hogyan fog kinézni a jövő.',
 '["Jövőbeli én", "Vision Board", "SMART Vision"]',
 'A vízió ad irányt, motivációt és összefogja a csapatot egy közös cél köré.',
 'Túl általános vízió nem inspirál. Túl részletes vízió megkötöz.',
 'Fogalmazd meg a víziódat: Mi a sikeres jövőállapot? Milyen hatásai vannak?'),

(2, 3, 'Stratégiai célok meghatározása',
 'A víziódat lebontani konkrét, mérhető célokra.',
 '["SMART célok", "OKR", "Balanced Scorecard"]',
 'A vízió nélkül célok = csak számmászás. Célok nélküli vízió = álmodozás.',
 'Túl sok cél = elveszett fókusz.',
 'Határozz meg 3-5 SMART célt: Specific, Measurable, Achievable, Relevant, Time-bound.'),

(2, 4, 'Vezetői stílus azonosítása',
 'Megérteni, milyen vezetői stílussal dolgozol természetesen.',
 '["Goleman 6 vezetői stílusa", "Situational Leadership", "Leadership Compass"]',
 'Nincs "legjobb" vezetői stílus – minden helyzethez más kell.',
 'A stílus-váltás nehéz és gyakorlást igényel.',
 'Értékeld magad az 6 vezetői stílus szerint 1-10 skálán. Mikor melyiket alkalmazod?'),

(2, 5, 'Akcióterv kidolgozása',
 'A stratégiai célokat lebontani konkrét, végrehajtható lépésekre.',
 '["Action Plan Template", "Gantt Chart", "RACI Matrix"]',
 'A stratégia nélkül a végrehajtás értelmetlen. A végrehajtás nélkül a stratégia haszontalan.',
 'Túl részletes terv merevvé válik.',
 'Készíts akciótervet: akció, felelős, határidő, erőforrás, KPI, státusz.'),

(2, 6, 'Döntéshozatali folyamat',
 'Kialakítani egy strukturált módszert a döntésekhez.',
 '["Döntési mátrix", "Pros & Cons", "Decision Tree"]',
 'A jó vezetők következetesen és strukturáltan döntenek.',
 'Minden döntési keretnek vannak korlátai.',
 'Definiáld a döntési folyamatodat: Mi alapján döntesz? Ki kell bevonni?'),

(2, 7, 'Kommunikációs terv',
 'Hogyan fogod kommunikálni a változást és stratégiát?',
 '["Stakeholder Map", "Kommunikációs mátrix", "Elevator Pitch"]',
 'A legjobb stratégia is kudarcot vall, ha nem kommunikálod megfelelően.',
 'A kommunikáció egyirányú lehet, ha nem figyelsz a visszajelzésekre.',
 'Készíts kommunikációs tervet: Ki? Mit? Mikor? Hogyan?'),

(2, 8, 'Kockázatelemzés és tervezés',
 'Azonosítsd a potenciális kockázatokat és készülj fel rájuk.',
 '["SWOT", "Risk Matrix", "Contingency Planning"]',
 'A felkészültség csökkenti a meglepetések hatását.',
 'Nem lehet minden kockázatra felkészülni.',
 'Végezz kockázatelemzést: Mi mehet rosszul? Milyen valószínű? Milyen hatása van?');

-- Additional days will be added similarly (Day 3-6)
-- For now, adding placeholder structure for Days 3-6

INSERT OR IGNORE INTO training_steps (day_id, step_number, title, description, tools, importance, limitations, instructions) VALUES 
(3, 1, 'Szerepek azonosítása', 
 'Határozd meg, milyen szerepekre és pozíciókra van szükség a stratégia végrehajtásához.',
 '["Szerepkör-elemzési mátrix", "WBS", "Stakeholder mapping", "Funkcionális térkép"]',
 'A rossz szerepek vagy hiányzó pozíciók a legjobb stratégiát is megbuktathatják.',
 'Túl sok szerepkör átfedésekhez vezet. Túl kevés túlterhelést okoz.',
 'Azonosítsd a kritikus szerepköröket és funkciókat a stratégiádhoz.'),

(3, 2, 'Kompetencia-elemzés',
 'Határozd meg minden szerepkörhöz a szükséges készségeket, tudást és tapasztalatokat.',
 '["Kompetencia profilok", "T-alakú készségmodell", "Kompetencia szótár", "360° értékelés"]',
 'A kompetenciák meghatározzák, milyen emberek kellenek a sikeres végrehajtáshoz.',
 'Túl részletes elvárások szűkítik a jelölteket. Túl általános leírások nem adnak útmutatást.',
 'Készíts kompetencia profilokat minden szerepkörhöz.'),

(3, 3, 'RACI mátrix',
 'Tisztázd minden kulcsfontosságú feladatnál, ki a felelős (R), elszámoltatható (A), konzultált (C) és tájékoztatott (I).',
 '["RACI mátrix sablon", "RACI workshopok", "Felelősségi térkép", "Döntéshozatali fa"]',
 '"Mindenki felelőssége = senki felelőssége." A RACI egyértelművé teszi a szerepeket.',
 'Túl részletes RACI nehézkessé válik. Túl általános nem ad elég útmutatást.',
 'Készítsd el a RACI mátrixot a főbb feladatokra és döntésekre.'),

(3, 4, 'Csapatstruktúra tervezése',
 'Tervezd meg, hogyan kapcsolódnak a szerepek, milyen jelentési vonalak lesznek, és hogyan működik a hierarchia.',
 '["Org Chart", "Span of Control elemzés", "Kommunikációs mátrix", "Csapatstruktúra modellek"]',
 'A struktúra határozza meg az információáramlást és a döntéshozatal sebességét.',
 'Túl hierarchikus struktúra lassít. Túl lapos struktúra káoszt okoz.',
 'Rajzold meg a csapat struktúráját és kommunikációs vonalait.'),

(3, 5, 'Tehetségértékelés',
 'Mérjed fel a meglévő csapattagok kompetenciáit és potenciálját.',
 '["9-Box Talent Grid", "Kompetencia assessment", "360° visszajelzés", "Teljesítmény-potenciál mátrix"]',
 'A megfelelő ember a megfelelő helyen sokszorosan hatékonyabb.',
 'Az értékelés szubjektív lehet. Több nézőpont szükséges.',
 'Értékeld a meglévő csapat tagjait: erősségek, fejlesztendő területek, potenciál.'),

(3, 6, 'Gap analízis',
 'Hasonlítsd össze a szükséges kompetenciákat a meglévőkkel, hogy láthasd a hiányosságokat.',
 '["Skills Gap Analysis", "Kompetencia térkép", "FTE elemzés", "Heatmap vizualizáció"]',
 'A gap analysis alapozza meg a fejlesztési és toborzási döntéseket.',
 'A jelenlegi kompetenciák értékelése szubjektív. Rendszeres felülvizsgálat szükséges.',
 'Készíts gap analízist: mely kompetenciák hiányoznak vagy elégtelenek?'),

(3, 7, 'Toborzási/fejlesztési terv',
 'A gap analysis alapján készíts konkrét akcióterveket: kit toborozni, kit fejleszteni, mikor és hogyan.',
 '["70-20-10 modell", "Toborzási csatorna elemzés", "L&D roadmap", "Make vs Buy vs Borrow"]',
 'A hiányosságok pótlása nélkül a stratégia nem valósítható meg.',
 'A toborzás időigényes. A fejlesztés eredménye bizonytalan. Alternatívákat is mérlegelj.',
 'Dolgozz ki akciótervet: kit kell toborozni, kit fejleszteni, milyen ütemezéssel.'),

(3, 8, 'Csapatösszetétel véglegesítése',
 'Az előző lépések alapján véglegesítsd a csapat összetételét, szerepköreit és működési kereteit.',
 '["Team Charter", "Szerepkör-leírások", "Csapatösszetételi mátrix", "Kick-off presentation"]',
 'A végső összefoglalás biztosítja, hogy mindenki tisztában legyen a szerepével.',
 'A papíron jó csapat a gyakorlatban másként működhet. Rendszeres adaptáció szükséges.',
 'Finalizáld a teljes csapat összetételét: ki-mit-mikor-hogyan.'),

(4, 1, 'KPI meghatározása',
 'Határozd meg azokat a kulcsfontosságú teljesítménymutatókat, amelyek valóban mérik a célok elérését.',
 '["SMART KPI", "Balanced Scorecard", "OKR", "Leading vs Lagging"]',
 'Néhány jó KPI többet ér, mint sok rossz. A KPI-ok irányítják a figyelmet.',
 'Túl sok KPI elveszíti a fókuszt. Nem minden fontos dolog mérhető könnyen.',
 'Válaszd ki a 3-7 legfontosabb KPI-t, ami tényleg mozgatja a célt.'),

(4, 2, 'Mérési rendszer kialakítása',
 'Hozz létre működő rendszert, amely konzisztensen és megbízhatóan gyűjti az adatokat.',
 '["Mérési terv", "Adatgyűjtési protokollok", "Automatizált rendszerek", "Data governance"]',
 'A rossz adat rosszabb, mint a hiányzó adat. A rendszeresség kulcsfontosságú.',
 'A manuális adatgyűjtés időigényes és hibázhat. A túlautomatizálás merev lehet.',
 'Tervezd meg, hogyan, mikor, ki gyűjti az adatokat és milyen minőségben.'),

(4, 3, 'Adatgyűjtési mechanizmusok',
 'Állítsd be a konkrét eszközöket és folyamatokat, amelyek biztosítják a pontos adatgyűjtést.',
 '["Automatizált eszközök", "API-k", "Űrlapok", "ETL folyamatok", "Adatintegráció"]',
 'Az automatizálás csökkenti a hibákat és növeli a gyorsaságot.',
 'Az integrációk összetettek lehetnek. Az adatminőség csak annyira jó, mint a forrás.',
 'Implementáld az adatgyűjtési eszközöket és folyamatokat.'),

(4, 4, 'Dashboard és reporting',
 'Készíts vizualizációkat és jelentéseket, amelyek egyszerűen mutatják a KPI-ok állását.',
 '["BI eszközök", "Power BI", "Tableau", "Real-time dashboards", "Vizualizáció"]',
 'Egy jó dashboard azonnal láthatóvá teszi a problémákat és trendeket.',
 'A túl zsúfolt dashboard használhatatlan. A valós idejű frissítés költséges lehet.',
 'Tervezd meg a dashboardokat és reporting struktúrát.'),

(4, 5, 'Visszajelzési rendszer',
 'Alakíts ki strukturált folyamatot, amely biztosítja az időben érkező konstruktív visszajelzéseket.',
 '["1-on-1 meetings", "SBI modell", "Feedforward", "360° visszajelzés"]',
 'A visszajelzés az egyik legerősebb fejlesztő eszköz.',
 'A rossz visszajelzés demotiváló. A túl késői visszajelzés értéktelen.',
 'Építsd be a visszajelzést a napi/heti rutinokba.'),

(4, 6, 'Teljesítményértékelési folyamat',
 'Alakíts ki strukturált, objektív értékelési folyamatot, amely összeköti az egyéni és szervezeti célokat.',
 '["Teljesítménymátrix", "OKR review", "Kompetencia értékelés", "Calibration"]',
 'A jó értékelés motivál és világos irányt ad. Az objektivitás kulcs.',
 'Az értékelés szubjektív lehet. A rating-ek torzításokat okozhatnak.',
 'Tervezd meg az értékelési folyamatot és kritériumokat.'),

(4, 7, 'Korrekciós mechanizmusok',
 'Építs be olyan rendszereket, amelyek jelzik a problémákat és segítenek gyorsan korrigálni.',
 '["Alert rendszerek", "Threshold-ok", "CAP", "5 Whys", "Fishbone", "PDCA"]',
 'A korai jelzés lehetővé teszi a gyors beavatkozást.',
 'A túl érzékeny alertek zajt okoznak. A tüneti kezelés nem old meg gyökérproblémákat.',
 'Állítsd be az alert rendszert és korrekciós folyamatokat.'),

(4, 8, 'Folyamatos fejlesztés',
 'Építsd be a folyamatos tanulás kultúráját, ahol a rendszer finomodik és alkalmazkodik.',
 '["Kaizen", "Retrospektívek", "A/B testing", "Learning reviews", "Continuous Improvement"]',
 'A rendszer folyamatos fejlesztése fenntartja a relevanciáját és hatékonyságát.',
 'A túl gyakori változtatás instabilitást okoz. A status quo ragadóssá válhat.',
 'Rendszeresítsd a retrospektíveket és fejlesztési ciklusokat.'),

(5, 1, 'Delegálási stratégia',
 'Tanuld meg, hogyan adj át feladatokat úgy, hogy az fejlessze a csapatot és felszabadítsa az idődet.',
 '["Eisenhower mátrix", "Skill-Will mátrix", "Delegálási szintek", "SMART feladatátadás"]',
 'A jó delegálás fejleszti a csapatot és felszabadítja a vezetőt. Empowerment eszköze.',
 'A rossz delegálás demotiváló. Túl sok kontroll fojtogat, túl kevés káoszt okoz.',
 'Gyakorold a delegálást: Mit? Kinek? Hogyan? Milyen felhatalmazással?'),

(5, 2, 'Motivációs tényezők',
 'Értsd meg, mi motiválja az embereket valójában, és alkalmazd tudatosan a vezetésben.',
 '["Herzberg Two-Factor", "Drive: Autonomy-Mastery-Purpose", "Motivációs térkép", "Stay Interview"]',
 'A motiváció nem egységes - minden ember más. A belső motiváció erősebb, mint a külső.',
 'Pénz rövid távú motivátor. A higiénés tényezők hiánya demotivál, de jelenléte nem motivál.',
 'Térképezd fel az egyéni motivációs tényezőket és alkalmazd őket.'),

(5, 3, 'Konfliktuskezelés',
 'Tanuld meg felismerni, kategorizálni és hatékonyan kezelni a konfliktusokat.',
 '["Thomas-Kilmann TKI", "Interest-Based Relational", "Mediáció", "Non-violent communication"]',
 'A jól kezelt konfliktus nem romboló, hanem építő. Kreativitás és innováció forrása.',
 'Az elfojtott konfliktus robban. A rossz kezelés mélyíti a problémát.',
 'Ismerd fel a konfliktus jeleit és avatkozz be időben, strukturáltan.'),

(5, 4, 'Pszichológiai biztonság építése',
 'Teremts olyan környezetet, ahol az emberek bátran kockáztathatnak, hibázhatnak és kérdezhetnek.',
 '["Google Project Aristotle", "Edmondson Safety Index", "Blameless postmortem", "Check-in rituals"]',
 'A pszichológiai biztonság a magas teljesítményű csapatok alapja. Innováció és tanulás előfeltétele.',
 'Nem jelenti az alacsony standardokat. Nem jelenti a felelősség hiányát.',
 'Építsd be a rituálékat és viselkedéseket, amelyek biztonságot teremtenek.'),

(5, 5, 'Coaching és mentoring',
 'Tanuld meg, hogyan fejleszd a csapattagokat coaching és mentoring segítségével.',
 '["GROW modell", "Socratic questioning", "Active listening", "70-20-10 fejlesztési modell"]',
 'A leader nem csak irányít, hanem fejleszt is. A coaching növeli az önállóságot és fejlődést.',
 'A coaching nem tanácsadás vagy utasítás. Időigényes és nem minden helyzetben megfelelő.',
 'Alkalmazd a GROW modellt és aktív hallgatást a fejlesztési beszélgetéseken.'),

(5, 6, 'Nehéz beszélgetések',
 'Készülj fel és bonyolítsd le hatékonyan a kényelmetelen beszélgetéseket.',
 '["Crucial Conversations", "SBI feedback", "PIE modell", "Nehéz beszélgetés checklist"]',
 'A nehéz beszélgetések elkerülése súlyosbítja a problémát. A jó előkészítés kulcs.',
 'Az érzelmek menedzselése nehéz. A timing kritikus. A defenzivitás természetes reakció.',
 'Használj strukturált kereteket és készülj fel érzelmileg is.'),

(5, 7, 'Csapatkohézió építése',
 'Építs erős, összetartó csapatot, ahol az emberek bíznak egymásban és együttműködnek.',
 '["Lencioni 5 Dysfunctions", "Team building", "Tuckman stages", "Team rituals"]',
 'A kohézió növeli a teljesítményt, csökkenti a fluktuációt és fokozza az elkötelezettséget.',
 'A túl erős kohézió groupthink-hez vezethet. Az új tagok integrálása kihívás.',
 'Építsd be a team rituals-t és hagyományokat, amelyek erősítik a kapcsolatokat.'),

(5, 8, 'Vezetői jelenléted tudatos alakítása',
 'Tudatosan formáld azt, hogyan vagy jelen vezetőként - kommunikációd, energiád, döntéseid.',
 '["Leadership Brand", "360° visszajelzés", "Vezetői napló", "Executive Presence"]',
 'A vezetői jelenlét modellt ad a csapatnak. Az autenticitás erősebb, mint a tökéletesség.',
 'Az önismeret hiánya vak foltokat okoz. A túlzott önreflexió béníthat.',
 'Használj rendszeres reflektív gyakorlatokat és kérj visszajelzést.'),

(6, 1, 'Változásbeépítési terv készítése',
 'A változások beágyazása a mindennapokba, hogy azok ne eseti akciók, hanem a működés természetes részei legyenek.',
 '["Change Impact Assessment", "Sustainability Checklist", "Anchoring Action Plan", "Habit Stacking Framework", "ADKAR Model"]',
 'A változás nem akkor történik meg, amikor meghozod a döntést, hanem amikor beépül a viselkedésbe. A legtöbb transzformáció azért bukik, mert nem fordítanak elég figyelmet a fenntartásra.',
 'Az emberek természetesen a korábbi szokásaikhoz húznak vissza, különösen nyomás alatt. A beépítés lassú folyamat, türelmet és következetességet igényel.',
 'Azonosítsd, mely új viselkedések/folyamatok kritikusak. Kapcsold őket meglévő rutinokhoz (habit stacking).'),

(6, 2, 'Standard munkafolyamatok (SOPs) és dokumentáció',
 'Rögzíteni a kulcsfontosságú folyamatokat világos, követhető formában, hogy bárki megérthesse és elvégezhesse.',
 '["SOP Template", "Process Mapping (SIPOC, Swimlane)", "Knowledge Base Platform", "Visual Work Instructions", "Process Documentation Framework"]',
 'A dokumentáció a szervezeti memória. Nélküle minden tudás emberekhez kötött, és fluktuáció esetén elvész.',
 'A dokumentáció önmagában nem elég - szükség van képzésre és folyamatos frissítésre is. Túl bonyolult SOP-k nem használhatóak.',
 'Azonosítsd a 10 legkritikusabb folyamatot. Dokumentáld őket lépésről lépésre, egyszerűen. Teszteld valós felhasználókkal.'),

(6, 3, 'Tudástranszfer és képzési rendszer',
 'A szervezeti tudás szétterítése, hogy ne csak a "tudók" szűk köre birtokolja a kritikus információkat.',
 '["Knowledge Transfer Plan", "Mentoring/Shadowing Program", "Communities of Practice", "Train-the-Trainer Program"]',
 'A szervezet okossága nem az egyének okosságának összege, hanem abban rejlik, hogyan osztják meg a tudást. A szétterülő tudás növeli a rugalmasságot.',
 'A tacit tudás (csendes tudás) nehezen formalizálható. Nem minden tudás transzferálható dokumentumokkal - kell a gyakorlat is.',
 'Térképezd fel a kritikus tudást és annak birtokosait. Párosíts szakértőket tanulókkal (mentoring). Építs be a rutinba a tudásmegosztást.'),

(6, 4, 'Monitoring és korai figyelmeztető rendszer',
 'Olyan mutatók és jelzések kiépítése, amelyek korai szakaszban jelzik, ha valami nem működik megfelelően.',
 '["Leading Indicators Dashboard", "Health Check Templates", "Pulse Surveys", "Red Flag Framework", "Control Charts"]',
 'Amit nem mérsz, azt nem tudod menedzselni. A korai figyelmeztető jelzők lehetővé teszik, hogy kisebb problémákat oldjunk meg, mielőtt válságokká nőnek.',
 'Túl sok mutató figyelmen kívül hagyáshoz vezet. Rossz mutatók hamis biztonságérzetet adnak. A monitoring önmagában nem old meg semmit.',
 'Határozd meg a fenntarthatóság KPI-jait. Állíts be automatikus riasztásokat. Definiálj vörös zászló indikátorokat.'),

(6, 5, 'Adaptációs képesség fejlesztése (Agility)',
 'Olyan szervezeti reflexek kiépítése, amelyek lehetővé teszik a gyors alkalmazkodást változó körülmények között.',
 '["Agile Framework (Scrum, Kanban)", "Scenario Planning", "Test-and-Learn Culture", "Retrospective Meetings", "OKR"]',
 'Nem a legerősebb túlél, hanem az, aki a legjobban alkalmazkodik a változáshoz. A rugalmasság versenyképességi előny a mai világban.',
 'A túl gyors változás káoszt okoz. Az agilitás nem jelenti azt, hogy nincs struktúra. Az egyensúly megtalálása nehéz.',
 'Építs be rövidebb tervezési ciklusokat. Hozz létre cross-funkcionális gyors csapatokat. Alkalmazz test and learn megközelítést.'),

(6, 6, 'Tanulási kultúra építése',
 'Olyan környezet teremtése, ahol a tanulás természetes része a munkának, és a hibák fejlődési lehetőségek.',
 '["Peter Senge 5 Disciplines", "After Action Review (AAR)", "Learning Circles", "Innovation Time (Google 20%)", "Failure Celebration Framework"]',
 'Az egyetlen tartós versenyelőny az, hogy képesek vagyunk gyorsabban tanulni, mint a versenytársaink. A tanulási kultúra a fenntartható fejlődés alapja.',
 'A büntetés kultúrája megöli a tanulást. Sok szervezet csak hirdet tanulási kultúrát, de nem él vele. Időt és erőforrást kell rászánni.',
 'Ünnepeld a produktív kudarcokat. Építs be reflection időt (retrospektívák). Támogass kísérletezést és innovációt.'),

(6, 7, 'Sikerkommunikáció és ünneplés',
 'A már elért eredmények rendszeres kommunikálása és megünneplése, ami erősíti a változást és a motivációt.',
 '["Success Story Template", "Recognition Program", "Communication Plan", "Celebration Rituals"]',
 'Az elismerés és ünneplés megerősíti a pozitív viselkedéseket. A látható sikerek növelik az elkötelezettséget és motivációt.',
 'Csak a nagy sikerek ünneplése demotiváló lehet. A túl gyakori vagy automatikus elismerés értékét veszti.',
 'Azonosítsd a quick wins-eket és kommunikáld őket. Ünnepelj mérföldköveket. Ossz meg tanulságokat is, ne csak sikereket.'),

(6, 8, 'Átadás és vezetői utódlástervezés',
 'A folytonosság biztosítása tudatos átadás és utódlástervezés révén, hogy a változások túléljék az eredeti vezetőt.',
 '["Succession Planning Framework", "9-Box Talent Grid", "Transition Roadmap", "Knowledge Handover Template", "Leadership Pipeline Model"]',
 'A nagy vezető nem azon méretik, mit ért el, hanem azon, mi történik távozása után. Az utódlástervezés biztosítja a folytonosságot.',
 'Sok vezető nehezen enged. A túl késői tervezés válságot okoz. Az utódok fejlesztése időt igényel.',
 'Azonosítsd a potenciális utódokat. Kezd el fejlesztésüket időben (6-12 hónap). Készíts részletes átadási tervet. Dokumentáld a láthatatlan dolgokat.');
